### ISSUE TITLE
ModuleNotFoundError: No module named 'ray'

### ISSUE THREAD

**Issue by Squ1shy** [amalrajan/learncpp-download#21]
File "C:\Users\-\Desktop\learncpp-download-master\source\main.py", line 3, in <module>
    import ray
ModuleNotFoundError: No module named 'ray'

**Comment by Squ1shy** [comment]
After running python main.py it shows this : 

_C:\Users\-\Documents\learncpp-download\source>python main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from helper import render
  File "C:\Users\-\Documents\learncpp-download\source\helper\render.py", line 10, in <module>
    import weasyprint
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\__init__.py", line 315, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\css\computed_values.py", line 9, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\text\ffi.py", line 398, in <module>
    gobject = _dlopen(
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\weasyprint\text\ffi.py", line 385, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\-\AppData\Local\Programs\Python\Python38\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'_

**Comment by 3b33** [comment]
> The ray module does not currently support Python 3.9+ (even though the docs say it does) There is an issue on the project about it, which is sadly still open meaning it hasn't been resolved. [ray-project/tune-sklearn#169](https://github.com/ray-project/tune-sklearn/issues/169) You can downgrade your python installation to 3.7/3.8 and install ray.

I have python 3.8.2 and still can't install ray. So maybe needs even older one.

**Comment by amalrajan** [comment]
Thank you for reporting. This issue is no longer applicable. For now, please stick with Python 3.10
