### ISSUE TITLE
AssignProcessToJobObject() failed

### ISSUE THREAD

**Issue by abhayhm** [amalrajan/learncpp-download#36]
# Error message:
(process:1140): GLib-GIO-WARNING **: 11:13:56.138: Unexpectedly, UWP app `Microsoft.ScreenSketch_11.2305.26.0_x64__8wekyb3d8bbwe' (AUMId `Microsoft.ScreenSketch_8wekyb3d8bbwe!App') supports 29 extensions but has no verbs
Traceback (most recent call last):
  File "C:\Users\abhayhm\Desktop\learncpp\learncpp-download\source\main.py", line 23, in <module>
    ray.init(log_to_driver=False)
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\worker.py", line 1534, in init
    _global_node = ray._private.node.Node(
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\node.py", line 287, in __init__
    self.start_head_processes()
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\node.py", line 1164, in start_head_processes
    self.start_monitor()
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\node.py", line 1067, in start_monitor
    process_info = ray._private.services.start_monitor(
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\services.py", line 1957, in start_monitor
    process_info = start_ray_process(
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\services.py", line 904, in start_ray_process
    ray._private.utils.set_kill_child_on_death_win32(process)
  File "C:\Users\abhayhm\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ray\_private\utils.py", line 916, in set_kill_child_on_death_win32
    raise OSError(ctypes.get_last_error(), "AssignProcessToJobObject() failed")
OSError: [Errno 0] AssignProcessToJobObject() failed

**Comment by Fieerce** [comment]
also got this issue when using python 3.10 from the microsoft store. installing it from python.org did it for me

**Comment by amalrajan** [comment]
Closing this issue, as it's not longer valid
