### ISSUE TITLE
WeasyPrint encounters a library loading issue related to 'gobject-2.0-0' on Windows

### ISSUE THREAD

**Issue by amalrajan** [amalrajan/learncpp-download#42]
### Error message:
```
WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
[Installation Steps](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation)
[Troubleshooting Guide](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting)

Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Documents\learncpp-download-master\source\main.py", line 5, in <module>
    from helper import render
  File "C:\Users\WDAGUtilityAccount\Documents\learncpp-download-master\source\helper\render.py", line 10, in <module>
    import weasyprint
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\weasyprint\__init__.py", line 387, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\weasyprint\css\__init__.py", line 25, in <module>
    from . import computed_values, counters, media_queries
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\weasyprint\css\computed_values.py", line 11, in <module>
    from ..text.ffi import ffi, pango, units_to_double
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\weasyprint\text\ffi.py", line 428, in <module>
    gobject = _dlopen(
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\weasyprint\text\ffi.py", line 417, in _dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'
```

### Steps to reproduce

1. Simply launch a new windows sandbox
2. Install Python 3.10
3. Run the script.

**Comment by samharrell24** [comment]
Had the same issue too.

**Comment by amalrajan** [comment]
Closing this issue as weasyprint is no longer a dependency
